/**
 * Fixture drawings for the moderation screen (src/moderation/).
 *
 * Two named sets:
 *   OFFENSIVE — marks the screen is meant to catch, in several proportions
 *               and at several rotations, drawn both solid and as outlines.
 *   INNOCENT  — ordinary things people draw at a public installation. NONE
 *               of these may be refused or held; that is the gate the
 *               thresholds in src/moderation/ are tuned against.
 *
 * Everything is generated by deterministic helpers with fixed parameters —
 * no randomness, no Date — matching ./strokes.ts.
 */

import type { Stroke, StrokeList } from '../../src/shape/types';
import {
  bird,
  capsule,
  circleBlob,
  disc,
  fish,
  hat,
  polyline,
  quadruped,
  ringOutline,
  scribble,
  snowman,
  squareOutline,
  stickFigure,
  triangleOutline,
} from './strokes';

// ── generators ───────────────────────────────────────────────────────────────

/** Rotate a stroke list about (0.5, 0.5) by `radians`. */
export function rotate(strokes: StrokeList, radians: number): StrokeList {
  const cos = Math.cos(radians);
  const sin = Math.sin(radians);
  return strokes.map((s) => ({
    w: s.w,
    pts: s.pts.map(([x, y, w]) => {
      const dx = x - 0.5;
      const dy = y - 0.5;
      return [0.5 + dx * cos - dy * sin, 0.5 + dx * sin + dy * cos, w] as [
        number,
        number,
        number,
      ];
    }),
  }));
}

/** Points along a circular arc. */
function arc(
  cx: number,
  cy: number,
  r: number,
  from: number,
  to: number,
  steps: number,
): [number, number][] {
  const pts: [number, number][] = [];
  for (let i = 0; i <= steps; i++) {
    const a = from + ((to - from) * i) / steps;
    pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
  }
  return pts;
}

/** A closed circle outline. */
function ring(cx: number, cy: number, r: number, w: number): Stroke {
  return polyline(arc(cx, cy, r, 0, Math.PI * 2, 36), w);
}

/**
 * The doodle, parameterised. Shaft runs upward from a base at (cx, cy);
 * two lobes of radius `ballR` sit either side of the base.
 */
export function phallusDoodle(opts: {
  cx?: number;
  cy?: number;
  shaftLen?: number;
  shaftW?: number;
  ballR?: number;
  outline?: boolean;
}): StrokeList {
  const cx = opts.cx ?? 0.5;
  const cy = opts.cy ?? 0.78;
  const shaftLen = opts.shaftLen ?? 0.44;
  const shaftW = opts.shaftW ?? 0.1;
  const ballR = opts.ballR ?? 0.085;
  const tipY = cy - shaftLen;
  if (opts.outline === true) {
    // Drawn as a contour: two circles and an open-bottomed shaft outline.
    return [
      ring(cx - ballR * 0.95, cy, ballR, 0.02),
      ring(cx + ballR * 0.95, cy, ballR, 0.02),
      polyline(
        [
          [cx - shaftW / 2, cy],
          [cx - shaftW / 2, tipY + shaftW / 2],
          ...arc(cx, tipY + shaftW / 2, shaftW / 2, Math.PI, Math.PI * 2, 10),
          [cx + shaftW / 2, cy],
        ],
        0.018,
      ),
    ];
  }
  return [
    capsule(cx, cy, cx, tipY, shaftW),
    disc(cx - ballR * 0.95, cy, ballR),
    disc(cx + ballR * 0.95, cy, ballR),
  ];
}

/** A four-fold bent-arm cross (swastika), as thick strokes. */
export function bentArmCross(opts: {
  arm?: number;
  bend?: number;
  w?: number;
  handed?: 1 | -1;
}): StrokeList {
  const arm = opts.arm ?? 0.3;
  const bend = opts.bend ?? 0.16;
  const w = opts.w ?? 0.05;
  const h = opts.handed ?? 1;
  const out: StrokeList = [];
  // Four arms, each a radial segment plus a right-angle foot.
  for (let k = 0; k < 4; k++) {
    const a = (k * Math.PI) / 2;
    const dx = Math.cos(a);
    const dy = Math.sin(a);
    const ex = 0.5 + dx * arm;
    const ey = 0.5 + dy * arm;
    // Foot turns 90 degrees, consistently handed.
    const fx = ex + -dy * bend * h;
    const fy = ey + dx * bend * h;
    out.push(capsule(0.5, 0.5, ex, ey, w));
    out.push(capsule(ex, ey, fx, fy, w));
  }
  return out;
}

// ── offensive set ────────────────────────────────────────────────────────────

/** The doodle in several proportions, rotations, and drawn as an outline. */
export const PHALLUS_SET: { name: string; strokes: StrokeList }[] = [
  { name: 'phallus classic', strokes: phallusDoodle({}) },
  {
    name: 'phallus long thin',
    strokes: phallusDoodle({ shaftLen: 0.56, shaftW: 0.07, ballR: 0.075, cy: 0.84 }),
  },
  {
    name: 'phallus short stubby',
    strokes: phallusDoodle({ shaftLen: 0.3, shaftW: 0.13, ballR: 0.1, cy: 0.72 }),
  },
  {
    name: 'phallus big lobes',
    strokes: phallusDoodle({ shaftLen: 0.4, shaftW: 0.08, ballR: 0.11, cy: 0.74 }),
  },
  { name: 'phallus rot 30', strokes: rotate(phallusDoodle({}), Math.PI / 6) },
  { name: 'phallus rot 90', strokes: rotate(phallusDoodle({}), Math.PI / 2) },
  { name: 'phallus rot 135', strokes: rotate(phallusDoodle({}), (Math.PI * 3) / 4) },
  { name: 'phallus rot 210', strokes: rotate(phallusDoodle({}), (Math.PI * 7) / 6) },
  {
    name: 'phallus rot 300 stubby',
    strokes: rotate(
      phallusDoodle({ shaftLen: 0.32, shaftW: 0.12, ballR: 0.1, cy: 0.72 }),
      (Math.PI * 5) / 3,
    ),
  },
  { name: 'phallus outline', strokes: phallusDoodle({ outline: true }) },
  {
    name: 'phallus outline rot 45',
    strokes: rotate(phallusDoodle({ outline: true }), Math.PI / 4),
  },
];

/** Four-fold bent-arm crosses: both handednesses, upright and tilted. */
export const CROSS_SET: { name: string; strokes: StrokeList }[] = [
  { name: 'bent cross right', strokes: bentArmCross({}) },
  { name: 'bent cross left', strokes: bentArmCross({ handed: -1 }) },
  { name: 'bent cross tilted', strokes: rotate(bentArmCross({}), Math.PI / 4) },
  { name: 'bent cross thick', strokes: bentArmCross({ w: 0.075, arm: 0.28, bend: 0.18 }) },
  { name: 'bent cross short feet', strokes: bentArmCross({ bend: 0.11 }) },
];

export const OFFENSIVE_SET = [...PHALLUS_SET, ...CROSS_SET];

// ── innocent set ─────────────────────────────────────────────────────────────

/** A cat: round head, two triangular ears, oval body, tail. */
export const cat: StrokeList = [
  disc(0.42, 0.34, 0.13), // head
  polyline([[0.32, 0.26], [0.3, 0.14], [0.4, 0.22]], 0.03), // left ear
  polyline([[0.52, 0.26], [0.55, 0.14], [0.45, 0.22]], 0.03), // right ear
  capsule(0.36, 0.55, 0.62, 0.55, 0.2), // body
  polyline([[0.72, 0.52], [0.8, 0.4], [0.76, 0.3]], 0.03), // tail
  capsule(0.4, 0.64, 0.4, 0.76, 0.045), // legs
  capsule(0.58, 0.64, 0.58, 0.76, 0.045),
];

/** A house: square walls with a triangular roof. */
export const house: StrokeList = [
  polyline(
    [[0.26, 0.86], [0.26, 0.5], [0.74, 0.5], [0.74, 0.86], [0.26, 0.86]],
    0.035,
  ),
  polyline([[0.2, 0.5], [0.5, 0.22], [0.8, 0.5]], 0.035),
];

/** A tree: straight trunk with a round crown — the closest innocent shape
 * to "shaft plus bulge", and the reason the twin-lobe test exists. */
export const tree: StrokeList = [
  capsule(0.5, 0.9, 0.5, 0.56, 0.07),
  disc(0.5, 0.4, 0.22),
];

/** A broccoli-ish tree with a two-lobed crown — a harder version of the
 * same trap: the bulge really does have two lobes, but at the wrong end
 * relative to the stem's base, and the lobes sit around the axis. */
export const twoLobeTree: StrokeList = [
  capsule(0.5, 0.92, 0.5, 0.6, 0.07),
  disc(0.4, 0.42, 0.17),
  disc(0.6, 0.42, 0.17),
];

/** A flower: stem, round centre, five petals. */
export const flower: StrokeList = [
  capsule(0.5, 0.94, 0.5, 0.58, 0.03),
  disc(0.5, 0.44, 0.08),
  ...[0, 1, 2, 3, 4].map((k) => {
    const a = (k / 5) * Math.PI * 2 - Math.PI / 2;
    return disc(0.5 + Math.cos(a) * 0.15, 0.44 + Math.sin(a) * 0.15, 0.075);
  }),
];

/** A pinwheel: four curved vanes, chiral like a bent-arm cross. */
export const pinwheel: StrokeList = [
  ...[0, 1, 2, 3].map((k) => {
    const a = (k / 4) * Math.PI * 2;
    const pts: [number, number][] = [];
    for (let i = 0; i <= 10; i++) {
      const t = i / 10;
      const ang = a + t * 1.1;
      const r = 0.3 * Math.sin(Math.PI * t) + 0.02;
      pts.push([0.5 + Math.cos(ang) * r, 0.5 + Math.sin(ang) * r]);
    }
    return polyline(pts, 0.05);
  }),
  capsule(0.5, 0.5, 0.5, 0.92, 0.025),
];

/** A solid-vaned pinwheel — four filled triangles, same handedness. */
export const pinwheelSolid: StrokeList = [0, 1, 2, 3].map((k) => {
  const a = (k / 4) * Math.PI * 2;
  const p = (ang: number, r: number): [number, number] => [
    0.5 + Math.cos(ang) * r,
    0.5 + Math.sin(ang) * r,
  ];
  return polyline([p(a, 0.04), p(a, 0.32), p(a + 0.7, 0.3), p(a, 0.04)], 0.035);
});

/** A plus sign: four equal arms, no bend. */
export const plusSign: StrokeList = [
  capsule(0.2, 0.5, 0.8, 0.5, 0.09),
  capsule(0.5, 0.2, 0.5, 0.8, 0.09),
];

/** A six-fold snowflake. */
export const snowflake: StrokeList = [0, 1, 2, 3, 4, 5].flatMap((k) => {
  const a = (k / 6) * Math.PI * 2;
  const ex = 0.5 + Math.cos(a) * 0.34;
  const ey = 0.5 + Math.sin(a) * 0.34;
  const mx = 0.5 + Math.cos(a) * 0.2;
  const my = 0.5 + Math.sin(a) * 0.2;
  return [
    capsule(0.5, 0.5, ex, ey, 0.03),
    capsule(mx, my, mx + Math.cos(a + 1) * 0.11, my + Math.sin(a + 1) * 0.11, 0.022),
    capsule(mx, my, mx + Math.cos(a - 1) * 0.11, my + Math.sin(a - 1) * 0.11, 0.022),
  ];
});

/** A five-point star outline. */
export const star: StrokeList = [
  polyline(
    [0, 1, 2, 3, 4, 5].map((k) => {
      const a = (k / 5) * Math.PI * 2 - Math.PI / 2;
      return [0.5 + Math.cos(a) * 0.36, 0.5 + Math.sin(a) * 0.36] as [number, number];
    }).flatMap((p, i, all) => {
      const next = all[(i + 1) % all.length]!;
      const mid: [number, number] = [(p[0] + next[0]) / 2, (p[1] + next[1]) / 2];
      const inner: [number, number] = [
        0.5 + (mid[0] - 0.5) * 0.42,
        0.5 + (mid[1] - 0.5) * 0.42,
      ];
      return [p, inner];
    }),
    0.035,
  ),
];

/** A heart: two round lobes over a point — twin lobes, no shaft. */
export const heart: StrokeList = [
  disc(0.38, 0.36, 0.15),
  disc(0.62, 0.36, 0.15),
  polyline([[0.24, 0.42], [0.5, 0.82], [0.76, 0.42]], 0.06),
];

/** A bone: round lobes at BOTH ends of a shaft. */
export const bone: StrokeList = [
  capsule(0.24, 0.5, 0.76, 0.5, 0.09),
  disc(0.22, 0.42, 0.075),
  disc(0.22, 0.58, 0.075),
  disc(0.78, 0.42, 0.075),
  disc(0.78, 0.58, 0.075),
];

/** A balloon on a string: round head on a long thin stem. */
export const balloon: StrokeList = [
  disc(0.5, 0.32, 0.2),
  capsule(0.5, 0.5, 0.54, 0.94, 0.018),
];

/** Two cherries on a stem — twin round lobes hanging off a stalk. */
export const cherries: StrokeList = [
  disc(0.36, 0.72, 0.14),
  disc(0.64, 0.72, 0.14),
  polyline([[0.36, 0.6], [0.5, 0.24], [0.64, 0.6]], 0.022),
];

/** A mushroom: fat stem, wide domed cap. */
export const mushroom: StrokeList = [
  capsule(0.5, 0.86, 0.5, 0.52, 0.14),
  polyline(arc(0.5, 0.5, 0.28, Math.PI, Math.PI * 2, 20), 0.08),
];

/** An ice cream cone: two scoops over a triangle. */
export const iceCream: StrokeList = [
  disc(0.42, 0.3, 0.13),
  disc(0.6, 0.3, 0.13),
  polyline([[0.3, 0.42], [0.5, 0.9], [0.72, 0.42]], 0.04),
];

/** A boat: hull with a mast and sail. */
export const boat: StrokeList = [
  polyline([[0.2, 0.68], [0.8, 0.68], [0.68, 0.84], [0.32, 0.84], [0.2, 0.68]], 0.035),
  capsule(0.5, 0.66, 0.5, 0.2, 0.025),
  polyline([[0.52, 0.22], [0.78, 0.6], [0.52, 0.6]], 0.03),
];

/** A car: body, roof, two wheels. */
export const car: StrokeList = [
  capsule(0.2, 0.58, 0.8, 0.58, 0.14),
  polyline([[0.34, 0.5], [0.4, 0.36], [0.62, 0.36], [0.68, 0.5]], 0.03),
  disc(0.34, 0.72, 0.08),
  disc(0.66, 0.72, 0.08),
];

/** A sun with rays. */
export const sun: StrokeList = [
  disc(0.5, 0.5, 0.16),
  ...[0, 1, 2, 3, 4, 5, 6, 7].map((k) => {
    const a = (k / 8) * Math.PI * 2;
    return capsule(
      0.5 + Math.cos(a) * 0.2,
      0.5 + Math.sin(a) * 0.2,
      0.5 + Math.cos(a) * 0.36,
      0.5 + Math.sin(a) * 0.36,
      0.03,
    );
  }),
];

/** An umbrella: canopy over a hooked handle. */
export const umbrella: StrokeList = [
  polyline(arc(0.5, 0.5, 0.32, Math.PI, Math.PI * 2, 24), 0.05),
  capsule(0.5, 0.5, 0.5, 0.86, 0.025),
  polyline(arc(0.42, 0.86, 0.08, 0, Math.PI, 10), 0.025),
];

/** A key: round bow, long stem, two teeth on one side. */
export const key: StrokeList = [
  ring(0.5, 0.24, 0.11, 0.035),
  capsule(0.5, 0.35, 0.5, 0.86, 0.04),
  capsule(0.5, 0.72, 0.64, 0.72, 0.035),
  capsule(0.5, 0.82, 0.64, 0.82, 0.035),
];

/** A pair of glasses: two rings and a bridge. */
export const glasses: StrokeList = [
  ring(0.32, 0.5, 0.15, 0.035),
  ring(0.68, 0.5, 0.15, 0.035),
  capsule(0.47, 0.5, 0.53, 0.5, 0.025),
];

/** A ladder. */
export const ladder: StrokeList = [
  capsule(0.36, 0.14, 0.36, 0.88, 0.035),
  capsule(0.64, 0.14, 0.64, 0.88, 0.035),
  ...[0.28, 0.44, 0.6, 0.76].map((y) => capsule(0.36, y, 0.64, y, 0.028)),
];

/** A rocket: pointed body with two fins at the base. */
export const rocket: StrokeList = [
  capsule(0.5, 0.34, 0.5, 0.8, 0.16),
  polyline([[0.42, 0.34], [0.5, 0.12], [0.58, 0.34]], 0.04),
  polyline([[0.42, 0.68], [0.28, 0.88], [0.42, 0.86]], 0.035),
  polyline([[0.58, 0.68], [0.72, 0.88], [0.58, 0.86]], 0.035),
];

/** A dumbbell: bar with a bulge at each end. */
export const dumbbell: StrokeList = [
  capsule(0.3, 0.5, 0.7, 0.5, 0.05),
  capsule(0.26, 0.36, 0.26, 0.64, 0.11),
  capsule(0.74, 0.36, 0.74, 0.64, 0.11),
];

/** A crab: wide body, two claws, six legs. */
export const crab: StrokeList = [
  capsule(0.36, 0.5, 0.64, 0.5, 0.24),
  disc(0.24, 0.36, 0.09),
  disc(0.76, 0.36, 0.09),
  ...[0.4, 0.5, 0.6].flatMap((x) => [
    capsule(x, 0.6, x - 0.06, 0.82, 0.028),
    capsule(1 - x, 0.6, 1 - x + 0.06, 0.82, 0.028),
  ]),
];

/** A spoon: round bowl on a straight handle. */
export const spoon: StrokeList = [
  polyline(arc(0.5, 0.28, 0.13, 0, Math.PI * 2, 20), 0.035),
  capsule(0.5, 0.42, 0.5, 0.9, 0.035),
];

/** A butterfly: two wing pairs about a body. */
export const butterfly: StrokeList = [
  capsule(0.5, 0.3, 0.5, 0.72, 0.035),
  disc(0.34, 0.4, 0.14),
  disc(0.66, 0.4, 0.14),
  disc(0.36, 0.64, 0.11),
  disc(0.64, 0.64, 0.11),
];

/** A cloud: three overlapping lobes. */
export const cloud: StrokeList = [
  disc(0.36, 0.52, 0.14),
  disc(0.5, 0.46, 0.18),
  disc(0.66, 0.53, 0.13),
  capsule(0.34, 0.6, 0.68, 0.6, 0.1),
];

/** A hot-air balloon: round envelope over a small basket. */
export const hotAirBalloon: StrokeList = [
  disc(0.5, 0.38, 0.24),
  capsule(0.44, 0.74, 0.56, 0.74, 0.06),
  capsule(0.42, 0.6, 0.45, 0.72, 0.015),
  capsule(0.58, 0.6, 0.55, 0.72, 0.015),
];

/** A four-leaf clover — four-fold, mirror-symmetric, not chiral. */
export const clover: StrokeList = [
  ...[0, 1, 2, 3].map((k) => {
    const a = (k / 4) * Math.PI * 2;
    return disc(0.5 + Math.cos(a) * 0.17, 0.5 + Math.sin(a) * 0.17, 0.14);
  }),
  capsule(0.5, 0.62, 0.56, 0.92, 0.02),
];

/** A spiral — chiral, but one arm, not four. */
export const spiral: StrokeList = [
  polyline(
    Array.from({ length: 48 }, (_, i) => {
      const t = (i / 47) * Math.PI * 5;
      const r = 0.03 + (t / (Math.PI * 5)) * 0.34;
      return [0.5 + Math.cos(t) * r, 0.5 + Math.sin(t) * r] as [number, number];
    }),
    0.03,
  ),
];

/** An arrow. */
export const arrow: StrokeList = [
  capsule(0.16, 0.5, 0.8, 0.5, 0.04),
  polyline([[0.62, 0.34], [0.86, 0.5], [0.62, 0.66]], 0.04),
];

/** A person with a round head and two legs — a snowman-ish stack that is
 * elongated with a bulge, one of the phallus detector's near neighbours. */
export const person: StrokeList = [
  disc(0.5, 0.24, 0.13),
  capsule(0.5, 0.36, 0.5, 0.66, 0.12),
  capsule(0.44, 0.66, 0.4, 0.9, 0.05),
  capsule(0.56, 0.66, 0.6, 0.9, 0.05),
];

/** A wide-open pair of scissors — an X with two ring handles. */
export const scissors: StrokeList = [
  capsule(0.3, 0.2, 0.68, 0.7, 0.03),
  capsule(0.7, 0.2, 0.32, 0.7, 0.03),
  ring(0.28, 0.76, 0.09, 0.025),
  ring(0.72, 0.76, 0.09, 0.025),
];

export const INNOCENT_SET: { name: string; strokes: StrokeList }[] = [
  { name: 'cat', strokes: cat },
  { name: 'house', strokes: house },
  { name: 'tree', strokes: tree },
  { name: 'two-lobe tree', strokes: twoLobeTree },
  { name: 'flower', strokes: flower },
  { name: 'pinwheel', strokes: pinwheel },
  { name: 'pinwheel solid', strokes: pinwheelSolid },
  { name: 'plus sign', strokes: plusSign },
  { name: 'snowflake', strokes: snowflake },
  { name: 'star', strokes: star },
  { name: 'heart', strokes: heart },
  { name: 'bone', strokes: bone },
  { name: 'balloon', strokes: balloon },
  { name: 'cherries', strokes: cherries },
  { name: 'mushroom', strokes: mushroom },
  { name: 'ice cream', strokes: iceCream },
  { name: 'boat', strokes: boat },
  { name: 'car', strokes: car },
  { name: 'sun', strokes: sun },
  { name: 'umbrella', strokes: umbrella },
  { name: 'key', strokes: key },
  { name: 'glasses', strokes: glasses },
  { name: 'ladder', strokes: ladder },
  { name: 'rocket', strokes: rocket },
  { name: 'dumbbell', strokes: dumbbell },
  { name: 'crab', strokes: crab },
  { name: 'spoon', strokes: spoon },
  { name: 'butterfly', strokes: butterfly },
  { name: 'cloud', strokes: cloud },
  { name: 'hot air balloon', strokes: hotAirBalloon },
  { name: 'clover', strokes: clover },
  { name: 'spiral', strokes: spiral },
  { name: 'arrow', strokes: arrow },
  { name: 'person', strokes: person },
  { name: 'scissors', strokes: scissors },
  { name: 'stick figure', strokes: stickFigure },
  { name: 'snowman', strokes: snowman },
  { name: 'fish', strokes: fish },
  { name: 'hat', strokes: hat },
  { name: 'scribble', strokes: scribble },
  { name: 'circle blob', strokes: circleBlob },
  { name: 'ring outline', strokes: ringOutline },
  { name: 'square outline', strokes: squareOutline },
  { name: 'triangle outline', strokes: triangleOutline },
  { name: 'bird', strokes: bird },
  { name: 'quadruped', strokes: quadruped },
  // Rotations of the near-miss shapes: a drawing arrives at any angle, and
  // the screen must not become angle-dependent on the innocent side either.
  { name: 'tree rot 45', strokes: rotate(tree, Math.PI / 4) },
  { name: 'tree rot 180', strokes: rotate(tree, Math.PI) },
  { name: 'bone rot 30', strokes: rotate(bone, Math.PI / 6) },
  { name: 'cherries rot 90', strokes: rotate(cherries, Math.PI / 2) },
  { name: 'heart rot 180', strokes: rotate(heart, Math.PI) },
  { name: 'balloon rot 135', strokes: rotate(balloon, (Math.PI * 3) / 4) },
  { name: 'mushroom rot 90', strokes: rotate(mushroom, Math.PI / 2) },
  { name: 'person rot 20', strokes: rotate(person, Math.PI / 9) },
  { name: 'pinwheel rot 30', strokes: rotate(pinwheel, Math.PI / 6) },
  { name: 'ice cream rot 200', strokes: rotate(iceCream, (Math.PI * 10) / 9) },
];
