/**
 * Hand-authored StrokeList fixtures for the shape pipeline tests.
 *
 * Everything here is generated by deterministic helpers with fixed
 * parameters — no randomness, no Date. Coordinates are [0,1] canvas space
 * (y-down); widths are fractions of canvas size, matching Stroke.w.
 */

import type { Stroke, StrokeList } from '../../src/shape/types';

/** A filled disc: a single stamped point whose width is the diameter. */
export function disc(cx: number, cy: number, r: number): Stroke {
  return { pts: [[cx, cy, 1]], w: r * 2 };
}

/** A straight capsule stroke from (x0,y0) to (x1,y1) with constant width. */
export function capsule(x0: number, y0: number, x1: number, y1: number, w: number): Stroke {
  return { pts: [[x0, y0, 1], [x1, y1, 1]], w };
}

/** A polyline stroke through the given points with constant width. */
export function polyline(pts: [number, number][], w: number): Stroke {
  return { pts: pts.map(([x, y]) => [x, y, 1] as [number, number, number]), w };
}

// ---------------------------------------------------------------------------
// Archetype fixtures
// ---------------------------------------------------------------------------

/** A filled circle centered on the canvas. Expected archetype: 'blob'. */
export const CIRCLE_RADIUS = 0.3;
export const circleBlob: StrokeList = [disc(0.5, 0.5, CIRCLE_RADIUS)];

/**
 * Snowman: two stacked lobes plus two legs reaching into the bottom 30% of
 * the ink bounds. Expected archetype: 'biped'.
 */
export const snowman: StrokeList = [
  disc(0.5, 0.62, 0.2), // body
  disc(0.5, 0.32, 0.13), // head
  capsule(0.42, 0.75, 0.42, 0.94, 0.05), // left leg
  capsule(0.58, 0.75, 0.58, 0.94, 0.05), // right leg
];

/**
 * A wide horizontal body with four downward legs.
 * Expected archetype: 'quadruped'.
 */
export const quadruped: StrokeList = [
  capsule(0.3, 0.45, 0.7, 0.45, 0.28), // body
  capsule(0.32, 0.5, 0.32, 0.8, 0.05),
  capsule(0.44, 0.5, 0.44, 0.8, 0.05),
  capsule(0.56, 0.5, 0.56, 0.8, 0.05),
  capsule(0.68, 0.5, 0.68, 0.8, 0.05),
];

/**
 * Tall bird: vertical oval body, two legs, one lateral wing stroke at
 * mid-height. Expected archetype: 'bird'.
 */
export const bird: StrokeList = [
  capsule(0.5, 0.3, 0.5, 0.62, 0.22), // vertical oval body
  capsule(0.45, 0.66, 0.45, 0.86, 0.045), // left leg
  capsule(0.55, 0.66, 0.55, 0.86, 0.045), // right leg
  capsule(0.55, 0.5, 0.8, 0.5, 0.05), // lateral wing, mid-height
];

// ---------------------------------------------------------------------------
// Degenerate fixtures
// ---------------------------------------------------------------------------

/** No strokes at all. */
export const empty: StrokeList = [];

/** A single tiny dot — below the usable-ink threshold. */
export const dot: StrokeList = [disc(0.5, 0.5, 0.003)];

/** A single hairline stroke. */
export const thinLine: StrokeList = [capsule(0.2, 0.5, 0.8, 0.5, 0.012)];

/**
 * Two disconnected blobs: a large one and a small stray one. The pipeline
 * keeps the large component and reports the discarded ink.
 */
export const disconnectedBlobs: StrokeList = [
  disc(0.35, 0.5, 0.22), // large
  disc(0.85, 0.2, 0.06), // small stray
];

/** Center of the small stray blob, for asserting it gets discarded. */
export const SMALL_BLOB_CENTER: [number, number] = [0.85, 0.2];

/** A dense zigzag scribble covering most of the canvas. */
export const scribble: StrokeList = [
  polyline(
    [
      [0.08, 0.1], [0.92, 0.14], [0.1, 0.24], [0.9, 0.3],
      [0.08, 0.4], [0.92, 0.46], [0.1, 0.56], [0.9, 0.62],
      [0.08, 0.72], [0.92, 0.78], [0.1, 0.88], [0.9, 0.92],
    ],
    0.08,
  ),
];
