/**
 * GENERATED — do not edit.
 *
 * `node scripts/katamari-curate.mjs --all --source <library-dir>` writes this
 * file from the library's `manifest.json` and the rules in `./rules.ts`. It is
 * a pure function of those two: same library, same rules, same bytes. Edit the
 * RULES, then re-run.
 *
 * 1510 models admitted out of 1703 exported
 * (208 excluded: the game's characters, the dummy rows and the
 * map-sized pieces); 182 of them are the ACTIVE set this world
 * draws — see `ACTIVE_BUDGET` in ./rules.ts. 29510 triangles,
 * 2.93 mb.
 */

import type { KatamariEntry } from './rules';

export const KATAMARI_ROWS: readonly KatamariEntry[] = [
  { id: "0007", name: "Canned Mackerel ", internalName: "CAN01_B", file: "0007_Canned_Mackerel.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "canned mackerel", hash: "7b6b95a1" },
  { id: "0012", name: "Fork", internalName: "FORK_B", file: "0012_Fork.glb", kind: "small", tier: "small", heightUnits: 0.11, rooted: false, label: "fork", hash: "04c71e79" },
  { id: "0018", name: "Telephone Book", internalName: "PBOOK_C", file: "0018_Telephone_Book.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "telephone book", hash: "c9a8f726" },
  { id: "001a", name: "New Year's Cards", internalName: "NENGA_B", file: "001a_New_Year_s_Cards.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "new year's cards", hash: "dfa6e487" },
  { id: "003c", name: "Burglar Mask", internalName: "OMEN02_B", file: "003c_Burglar_Mask.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "burglar mask", hash: "891d1f1b" },
  { id: "0050", name: "Shrimp Sushi", internalName: "SUSHI06_A", file: "0050_Shrimp_Sushi.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, beach: true, label: "shrimp sushi", hash: "3321a03c" },
  { id: "0058", name: "Chicken Egg", internalName: "EGG03_B", file: "0058_Chicken_Egg.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "chicken egg", hash: "6d0b2b74" },
  { id: "006b", name: "Barrel", internalName: "TARU_D", file: "006b_Barrel.glb", kind: "medium", tier: "medium", heightUnits: 0.75, rooted: false, label: "barrel", hash: "a3e6db0a" },
  { id: "006d", name: "X'mas Tree", internalName: "XMAS01_D", file: "006d_X_mas_Tree.glb", kind: "conifer", tier: "medium", heightUnits: 4, rooted: true, hash: "cb5ba163" },
  { id: "0073", name: "Blue Ornament", internalName: "XMAS07_B", file: "0073_Blue_Ornament.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "blue ornament", hash: "f0b8af28" },
  { id: "0085", name: "Weather Station", internalName: "HYAKUBOX_D", file: "0085_Weather_Station.glb", kind: "waterTower", tier: "large", heightUnits: 5, rooted: true, hash: "38361163" },
  { id: "00a3", name: "Water Tank", internalName: "WATERTANK_F", file: "00a3_Water_Tank.glb", kind: "waterTower", tier: "large", heightUnits: 5.51, rooted: true, hash: "92e9a42d" },
  { id: "00a6", name: "Radio Tower", internalName: "DENTOWER_G", file: "00a6_Radio_Tower.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, hash: "8d5008ed" },
  { id: "00aa", name: "Boat", internalName: "BOAT01_E", file: "00aa_Boat.glb", kind: "small", tier: "small", heightUnits: 0.47, rooted: false, beach: true, label: "boat", hash: "e0bca4fa" },
  { id: "00ab", name: "Propane Tank", internalName: "GASS01_D", file: "00ab_Propane_Tank.glb", kind: "waterTower", tier: "large", heightUnits: 5, rooted: true, hash: "57b907b7" },
  { id: "00ae", name: "Binoculars", internalName: "VIEWSPOT02_D", file: "00ae_Binoculars.glb", kind: "medium", tier: "medium", heightUnits: 1.41, rooted: false, label: "binoculars", hash: "349a7509" },
  { id: "00b0", name: "Swan Boat", internalName: "BOAT02_E", file: "00b0_Swan_Boat.glb", kind: "medium", tier: "medium", heightUnits: 1.98, rooted: false, beach: true, label: "swan boat", hash: "52c78456" },
  { id: "00b8", name: "Bucket", internalName: "DUSTBOX03_C", file: "00b8_Bucket.glb", kind: "medium", tier: "medium", heightUnits: 0.6, rooted: false, label: "bucket", hash: "411e2dd1" },
  { id: "00bb", name: "Pier", internalName: "SANBASHI_F", file: "00bb_Pier.glb", kind: "large", tier: "large", heightUnits: 3.13, rooted: false, beach: true, label: "pier", hash: "16768ebc" },
  { id: "00c0", name: "Parasol", internalName: "UMBRELLA03_C", file: "00c0_Parasol.glb", kind: "medium", tier: "medium", heightUnits: 1.16, rooted: false, beach: true, label: "parasol", hash: "f26ddd51" },
  { id: "00c4", name: "Kerosene Tank", internalName: "POLYTANK01_C", file: "00c4_Kerosene_Tank.glb", kind: "waterTower", tier: "large", heightUnits: 5, rooted: true, hash: "bcd3b933" },
  { id: "00cd", name: "Plastic Greenhouse", internalName: "FARMHOUSE02_F", file: "00cd_Plastic_Greenhouse.glb", kind: "large", tier: "large", heightUnits: 3.54, rooted: false, label: "plastic greenhouse", hash: "48b5aa9f" },
  { id: "00d0", name: "Matsuri Table", internalName: "TENT03B_E", file: "00d0_Matsuri_Table.glb", kind: "picnicTable", tier: "medium", heightUnits: 1, rooted: true, hash: "8775bc81" },
  { id: "00d2", name: "Picnic Table", internalName: "VIEWSPOT01_F", file: "00d2_Picnic_Table.glb", kind: "picnicTable", tier: "medium", heightUnits: 2.91, rooted: true, hash: "cc30b386" },
  { id: "00d4", name: "Ramen Shop", internalName: "SHOPCH01_G", file: "00d4_Ramen_Shop.glb", kind: "building", tier: "building", heightUnits: 4.23, rooted: true, hash: "3bd67135" },
  { id: "00e0", name: "Fence", internalName: "FENCE02_F", file: "00e0_Fence.glb", kind: "large", tier: "large", heightUnits: 2.44, rooted: true, label: "fence", hash: "b39402f3" },
  { id: "00e9", name: "Garden Plant (M)", internalName: "PLANT01_D", file: "00e9_Garden_Plant_M.glb", kind: "bush", tier: "small", heightUnits: 1.15, rooted: true, hash: "0a1b3b0f" },
  { id: "00f1", name: "Lamp Post", internalName: "TOWNLIGHT01_E", file: "00f1_Lamp_Post.glb", kind: "large", tier: "large", heightUnits: 3.76, rooted: true, label: "lamp post", hash: "b732abd5" },
  { id: "00f9", name: "Phone Booth", internalName: "TOWNPHONE02_E", file: "00f9_Phone_Booth.glb", kind: "large", tier: "large", heightUnits: 2.38, rooted: true, label: "phone booth", hash: "3cec3ff5" },
  { id: "00fa", name: "Motoki Residence", internalName: "HOUSE06_F", file: "00fa_Motoki_Residence.glb", kind: "building", tier: "building", heightUnits: 4.68, rooted: true, hash: "67926ee9" },
  { id: "00fb", name: "Small Tree", internalName: "TREE09_E", file: "00fb_Small_Tree.glb", kind: "tree", tier: "medium", heightUnits: 4.18, rooted: true, hash: "d3f86bc8" },
  { id: "0105", name: "Palm Tree", internalName: "TREE10_E", file: "0105_Palm_Tree.glb", kind: "palm", tier: "medium", heightUnits: 5.04, rooted: true, beach: true, hash: "2a19352a" },
  { id: "0106", name: "Farmhouse", internalName: "FARMHOUSE01_G", file: "0106_Farmhouse.glb", kind: "large", tier: "large", heightUnits: 4.09, rooted: false, label: "farmhouse", hash: "b3d09abe" },
  { id: "010f", name: "Roach Motel", internalName: "GOKIHOUSE01_C", file: "010f_Roach_Motel.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "roach motel", hash: "1fe3873d" },
  { id: "0111", name: "Falling Rock", internalName: "ROLLINGSTONE01_E", file: "0111_Falling_Rock.glb", kind: "rock", tier: "small", heightUnits: 1.72, rooted: false, beach: true, inland: true, hash: "9828a197" },
  { id: "0113", name: "Pine Decoration", internalName: "NEWYEARPLANT_D", file: "0113_Pine_Decoration.glb", kind: "conifer", tier: "medium", heightUnits: 4, rooted: true, hash: "4e4baf96" },
  { id: "0114", name: "Regular Tree", internalName: "TREE01_F", file: "0114_Regular_Tree.glb", kind: "tree", tier: "medium", heightUnits: 5.6, rooted: true, hash: "d875f6dc" },
  { id: "0115", name: "Big Tree", internalName: "TREE02_G", file: "0115_Big_Tree.glb", kind: "tree", tier: "medium", heightUnits: 6.39, rooted: true, hash: "f7b0eafe" },
  { id: "0120", name: "Striped Fish", internalName: "FISH11_B", file: "0120_Striped_Fish.glb", kind: "small", tier: "small", heightUnits: 0.17, rooted: false, beach: true, inland: true, label: "striped fish", hash: "631c1732" },
  { id: "0125", name: "Street Stall", internalName: "DEMISE01_E", file: "0125_Street_Stall.glb", kind: "picnicTable", tier: "medium", heightUnits: 2.35, rooted: true, hash: "0c1882ff" },
  { id: "0134", name: "Construction Fence", internalName: "FENCE07_F", file: "0134_Construction_Fence.glb", kind: "large", tier: "large", heightUnits: 2.82, rooted: true, label: "construction fence", hash: "d4ea8b2c" },
  { id: "0136", name: "Bus", internalName: "BUS01_F", file: "0136_Bus.glb", kind: "large", tier: "large", heightUnits: 3.06, rooted: false, label: "bus", hash: "cc7eea42" },
  { id: "0137", name: "Carp Streamer", internalName: "SKYCARP01_F", file: "0137_Carp_Streamer.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, hash: "4fa7cb2a" },
  { id: "013c", name: "Spirit of Joy", internalName: "STATUE02_E", file: "013c_Spirit_of_Joy.glb", kind: "large", tier: "large", heightUnits: 3.24, rooted: false, label: "spirit of joy", hash: "76f7cd32" },
  { id: "0141", name: "Slide", internalName: "YUGU05_E", file: "0141_Slide.glb", kind: "large", tier: "large", heightUnits: 2.79, rooted: false, label: "slide", hash: "7cdd81ac" },
  { id: "0147", name: "Tricycle", internalName: "CYCLE02_D", file: "0147_Tricycle.glb", kind: "medium", tier: "medium", heightUnits: 1.14, rooted: false, label: "tricycle", hash: "9a7efa6b" },
  { id: "014b", name: "Monument", internalName: "STONE01_E", file: "014b_Monument.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "d3937965" },
  { id: "014d", name: "Water Tap", internalName: "WATEREXIT_C", file: "014d_Water_Tap.glb", kind: "medium", tier: "medium", heightUnits: 0.96, rooted: false, label: "water tap", hash: "fbde3541" },
  { id: "014e", name: "Daruma", internalName: "DARUMA01_C", file: "014e_Daruma.glb", kind: "cactus", tier: "small", heightUnits: 1.5, rooted: true, hash: "1f4a3ab3" },
  { id: "015b", name: "Picnic Basket", internalName: "PICNIC01_C", file: "015b_Picnic_Basket.glb", kind: "picnicTable", tier: "medium", heightUnits: 1, rooted: true, hash: "f9d199c6" },
  { id: "015f", name: "Lion Statue", internalName: "STATUE04_E", file: "015f_Lion_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "ab957ed1" },
  { id: "016f", name: "Pampas Grass", internalName: "SUSUKI01_C", file: "016f_Pampas_Grass.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "4aafd15b" },
  { id: "0170", name: "Dragon Statue", internalName: "SHOPCH03_G", file: "0170_Dragon_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "f154d27b" },
  { id: "017b", name: "Oil Tank", internalName: "OILTANK_G", file: "017b_Oil_Tank.glb", kind: "waterTower", tier: "large", heightUnits: 8, rooted: true, hash: "f58c9d21" },
  { id: "0191", name: "Airport Terminal", internalName: "AIRPORT02_G", file: "0191_Airport_Terminal.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, hash: "8b2281d5" },
  { id: "01a4", name: "Long Screw", internalName: "VIS02_A", file: "01a4_Long_Screw.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "long screw", hash: "24e3dbe1" },
  { id: "01a8", name: "Bulldozer", internalName: "WORKCAR04_F", file: "01a8_Bulldozer.glb", kind: "large", tier: "large", heightUnits: 3.15, rooted: false, label: "bulldozer", hash: "63f7c603" },
  { id: "01b0", name: "Driller", internalName: "TANK01_F", file: "01b0_Driller.glb", kind: "large", tier: "large", heightUnits: 3.27, rooted: false, label: "driller", hash: "6334c325" },
  { id: "01b4", name: "Shogi Table", internalName: "SHOGIBAN_C", file: "01b4_Shogi_Table.glb", kind: "picnicTable", tier: "medium", heightUnits: 1, rooted: true, hash: "91e0c6b2" },
  { id: "01bf", name: "Boy's Backpack", internalName: "RANDSEL02_C", file: "01bf_Boy_s_Backpack.glb", kind: "small", tier: "small", heightUnits: 0.3, rooted: false, label: "boy's backpack", hash: "03555f97" },
  { id: "01ce", name: "Cowshed", internalName: "COWSHED_G", file: "01ce_Cowshed.glb", kind: "large", tier: "large", heightUnits: 3.42, rooted: false, label: "cowshed", hash: "3b3b4e64" },
  { id: "01cf", name: "Log Fence", internalName: "SAKU07_E", file: "01cf_Log_Fence.glb", kind: "stump", tier: "small", heightUnits: 1.83, rooted: true, hash: "bf28511e" },
  { id: "01d8", name: "Kintaro-Bear", internalName: "BEAR05_F", file: "01d8_Kintaro-Bear.glb", kind: "large", tier: "large", heightUnits: 2.18, rooted: false, label: "kintaro-bear", hash: "e09fd931" },
  { id: "01e4", name: "Spider Crab", internalName: "CRAB05_C", file: "01e4_Spider_Crab.glb", kind: "small", tier: "small", heightUnits: 0.28, rooted: false, beach: true, label: "spider crab", hash: "fc9f8b4a" },
  { id: "01e5", name: "Blue Crab", internalName: "CRAB06_C", file: "01e5_Blue_Crab.glb", kind: "small", tier: "small", heightUnits: 0.13, rooted: false, beach: true, label: "blue crab", hash: "6bf3946f" },
  { id: "01e6", name: "Calf", internalName: "COW01_D", file: "01e6_Calf.glb", kind: "small", tier: "small", heightUnits: 0.54, rooted: false, label: "calf", hash: "4e336821" },
  { id: "0216", name: "Tall Schoolboy", internalName: "MANDANSHI01_D", file: "0216_Tall_Schoolboy.glb", kind: "large", tier: "large", heightUnits: 2.29, rooted: false, label: "tall schoolboy", hash: "bbdb438e" },
  { id: "0242", name: "Double Punk", internalName: "MANBIKE03_E", file: "0242_Double_Punk.glb", kind: "medium", tier: "medium", heightUnits: 1.51, rooted: false, label: "double punk", hash: "41f603fe" },
  { id: "024a", name: "Busker", internalName: "MANMUSIC01_D", file: "024a_Busker.glb", kind: "large", tier: "large", heightUnits: 2.24, rooted: false, label: "busker", hash: "3ecc3741" },
  { id: "0252", name: "Fortune-teller", internalName: "MANURANAI_D", file: "0252_Fortune-teller.glb", kind: "medium", tier: "medium", heightUnits: 1.49, rooted: false, label: "fortune-teller", hash: "2e6670c1" },
  { id: "025a", name: "Huge Tree", internalName: "TREE03_D", file: "025a_Huge_Tree.glb", kind: "tree", tier: "medium", heightUnits: 8, rooted: true, hash: "7fe3586d" },
  { id: "025b", name: "Gigantic Tree", internalName: "TREE04_D", file: "025b_Gigantic_Tree.glb", kind: "tree", tier: "medium", heightUnits: 8, rooted: true, hash: "90168b16" },
  { id: "0264", name: "Supermarket", internalName: "SUPER01_G", file: "0264_Supermarket.glb", kind: "large", tier: "large", heightUnits: 5.26, rooted: false, label: "supermarket", hash: "9475ead9" },
  { id: "0266", name: "Kelp Factory", internalName: "FACTORY01_G", file: "0266_Kelp_Factory.glb", kind: "building", tier: "building", heightUnits: 10.29, rooted: true, hash: "89084754" },
  { id: "0278", name: "Big Turnip", internalName: "DAIKON03_F", file: "0278_Big_Turnip.glb", kind: "building", tier: "building", heightUnits: 10.42, rooted: true, hash: "89e301a5" },
  { id: "0282", name: "Cherry Tree", internalName: "TREE05_E", file: "0282_Cherry_Tree.glb", kind: "tree", tier: "medium", heightUnits: 4.39, rooted: true, hash: "6f1c3a8e" },
  { id: "0288", name: "Small Fishing Boat", internalName: "FISHSHIP01_F", file: "0288_Small_Fishing_Boat.glb", kind: "large", tier: "large", heightUnits: 3.67, rooted: false, beach: true, label: "small fishing boat", hash: "7e53e978" },
  { id: "0289", name: "Fishing Boat", internalName: "FISHSHIP02_F", file: "0289_Fishing_Boat.glb", kind: "large", tier: "large", heightUnits: 4.03, rooted: false, beach: true, label: "fishing boat", hash: "797fc1e5" },
  { id: "02a4", name: "Horizontal Bar", internalName: "YUGU06_E", file: "02a4_Horizontal_Bar.glb", kind: "large", tier: "large", heightUnits: 2.91, rooted: false, label: "horizontal bar", hash: "a07ab1ef" },
  { id: "02a7", name: "Principal's Statue", internalName: "STATUE05_E", file: "02a7_Principal_s_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "a3fc65bf" },
  { id: "02af", name: "Lollipop", internalName: "AME01_B", file: "02af_Lollipop.glb", kind: "small", tier: "small", heightUnits: 0.24, rooted: false, label: "lollipop", hash: "543dd52d" },
  { id: "02b1", name: "Boat Rental Sign", internalName: "WATERMILL02_C", file: "02b1_Boat_Rental_Sign.glb", kind: "medium", tier: "medium", heightUnits: 1.75, rooted: true, beach: true, label: "boat rental sign", hash: "a6524469" },
  { id: "02b7", name: "Tree", internalName: "TREE06_E", file: "02b7_Tree.glb", kind: "tree", tier: "medium", heightUnits: 6, rooted: true, hash: "1788ba2d" },
  { id: "02ba", name: "Butterfly Specimens", internalName: "MUSHISAMPLE01_C", file: "02ba_Butterfly_Specimens.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "butterfly specimens", hash: "112d2faf" },
  { id: "02c0", name: "School Clocktower", internalName: "SCHOOL04_G", file: "02c0_School_Clocktower.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, hash: "b104447c" },
  { id: "02c3", name: "Kimono", internalName: "KIMONO_E", file: "02c3_Kimono.glb", kind: "medium", tier: "medium", heightUnits: 1.64, rooted: false, label: "kimono", hash: "9f586a69" },
  { id: "02da", name: "Bear-Man", internalName: "MANANIMAL02_D", file: "02da_Bear-Man.glb", kind: "large", tier: "large", heightUnits: 2.19, rooted: false, label: "bear-man", hash: "38f6aacd" },
  { id: "02e5", name: "Tree Frog", internalName: "FLOG01_A", file: "02e5_Tree_Frog.glb", kind: "tree", tier: "medium", heightUnits: 3, rooted: true, hash: "c535ac89" },
  { id: "02f8", name: "Garden Rock", internalName: "NIWAGOODS02_D", file: "02f8_Garden_Rock.glb", kind: "rock", tier: "small", heightUnits: 0.6, rooted: false, beach: true, inland: true, hash: "23ce9699" },
  { id: "02fb", name: "Tree Stump", internalName: "TREE07_C", file: "02fb_Tree_Stump.glb", kind: "stump", tier: "small", heightUnits: 0.6, rooted: true, hash: "892f2084" },
  { id: "02fc", name: "Medium Tree", internalName: "TREE08_E", file: "02fc_Medium_Tree.glb", kind: "tree", tier: "medium", heightUnits: 3.82, rooted: true, hash: "733553c0" },
  { id: "02fd", name: "Pink Flower", internalName: "FLOWER01_A", file: "02fd_Pink_Flower.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "7acfd385" },
  { id: "02fe", name: "White Flower", internalName: "FLOWER02_A", file: "02fe_White_Flower.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "b552eb80" },
  { id: "0303", name: "Sand Castle", internalName: "SANDSPOT04_C", file: "0303_Sand_Castle.glb", kind: "building", tier: "building", heightUnits: 2.4, rooted: true, beach: true, hash: "12a8f0be" },
  { id: "0317", name: "Water Tank Sign", internalName: "WATERTANK02_D", file: "0317_Water_Tank_Sign.glb", kind: "waterTower", tier: "large", heightUnits: 5, rooted: true, hash: "0c4d2f55" },
  { id: "0318", name: "No Parking!", internalName: "KANBAN08_D", file: "0318_No_Parking.glb", kind: "medium", tier: "medium", heightUnits: 1.34, rooted: false, label: "no parking!", hash: "11dfe26c" },
  { id: "031c", name: "Swing", internalName: "TREE08B_D", file: "031c_Swing.glb", kind: "medium", tier: "medium", heightUnits: 1.37, rooted: false, label: "swing", hash: "6c0049da" },
  { id: "0330", name: "Lime Crayon", internalName: "CRAYON06_B", file: "0330_Lime_Crayon.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "lime crayon", hash: "44d92ee2" },
  { id: "034c", name: "Sausage", internalName: "HAM02_B", file: "034c_Sausage.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "sausage", hash: "2938438f" },
  { id: "034d", name: "RC Controller", internalName: "RADICON01_C", file: "034d_RC_Controller.glb", kind: "small", tier: "small", heightUnits: 0.18, rooted: false, label: "rc controller", hash: "a7249ecd" },
  { id: "035b", name: "Round Table", internalName: "TABLE02_E", file: "035b_Round_Table.glb", kind: "picnicTable", tier: "medium", heightUnits: 1, rooted: true, hash: "e9f23f12" },
  { id: "0369", name: "Cherry Tree", internalName: "HOMEFIELD02_C", file: "0369_Cherry_Tree.glb", kind: "tree", tier: "medium", heightUnits: 3, rooted: true, hash: "911090b1" },
  { id: "036a", name: "Cucumber Plant", internalName: "HOMEFIELD03_C", file: "036a_Cucumber_Plant.glb", kind: "bush", tier: "small", heightUnits: 0.61, rooted: true, hash: "4a90f355" },
  { id: "0382", name: "Helicopter", internalName: "PLANE02_F", file: "0382_Helicopter.glb", kind: "large", tier: "large", heightUnits: 2.67, rooted: false, label: "helicopter", hash: "35af851c" },
  { id: "0392", name: "Rich Haul Flag #4", internalName: "FLAG04_F", file: "0392_Rich_Haul_Flag_4.glb", kind: "building", tier: "building", heightUnits: 6.29, rooted: true, hash: "a0f80016" },
  { id: "039d", name: "Tsunami Island", internalName: "ISLAND06_G", file: "039d_Tsunami_Island.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, beach: true, hash: "81599ae4" },
  { id: "03a2", name: "Pedestrian Signal", internalName: "SIGNAL02_E", file: "03a2_Pedestrian_Signal.glb", kind: "large", tier: "large", heightUnits: 3.38, rooted: true, label: "pedestrian signal", hash: "7cebbe0d" },
  { id: "03a9", name: "Rock", internalName: "PEBBLE01_C", file: "03a9_Rock.glb", kind: "rock", tier: "small", heightUnits: 0.6, rooted: false, beach: true, inland: true, hash: "8e9a2e84" },
  { id: "03aa", name: "Black Rock", internalName: "PEBBLE02_C", file: "03aa_Black_Rock.glb", kind: "rock", tier: "small", heightUnits: 0.6, rooted: false, beach: true, inland: true, hash: "fe835aac" },
  { id: "03ab", name: "Big Rock", internalName: "PEBBLE03_C", file: "03ab_Big_Rock.glb", kind: "rock", tier: "small", heightUnits: 0.6, rooted: false, beach: true, inland: true, hash: "5985bbb6" },
  { id: "03cc", name: "Umbrella Shop Sign", internalName: "SHOPKASA02_D", file: "03cc_Umbrella_Shop_Sign.glb", kind: "building", tier: "building", heightUnits: 2.4, rooted: true, hash: "24aa0903" },
  { id: "03d0", name: "Flower Pot", internalName: "FLOWERPOT02_D", file: "03d0_Flower_Pot.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "5ef15a1f" },
  { id: "03db", name: "Onigiri (Rice Ball)", internalName: "ONIGIRI01_B", file: "03db_Onigiri_Rice_Ball.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "onigiri (rice ball)", hash: "4df68051" },
  { id: "03e7", name: "Dove Statue", internalName: "STATUE06_E", file: "03e7_Dove_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "db61d64b" },
  { id: "03e8", name: "Girl Statue", internalName: "STATUE07_E", file: "03e8_Girl_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3.25, rooted: true, hash: "f3cda287" },
  { id: "03e9", name: "Fish Statue", internalName: "STATUE08_E", file: "03e9_Fish_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, beach: true, inland: true, hash: "d90968a1" },
  { id: "03ea", name: "Bear Cub Statue", internalName: "STATUE09_E", file: "03ea_Bear_Cub_Statue.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "d2178278" },
  { id: "03ef", name: "Baby Turtle", internalName: "KAMEEGGB_A", file: "03ef_Baby_Turtle.glb", kind: "small", tier: "small", heightUnits: 0.35, rooted: false, beach: true, label: "baby turtle", hash: "1f276e80" },
  { id: "03f6", name: "Parasol", internalName: "UMBRELLA03B_C", file: "03f6_Parasol.glb", kind: "medium", tier: "medium", heightUnits: 1.16, rooted: false, beach: true, label: "parasol", hash: "631f7134" },
  { id: "03fe", name: "Sperm Whale", internalName: "WHALE01_G", file: "03fe_Sperm_Whale.glb", kind: "large", tier: "large", heightUnits: 4.08, rooted: false, beach: true, label: "sperm whale", hash: "58bc7648" },
  { id: "03ff", name: "Gigantic Squid", internalName: "OCTOPUS01_G", file: "03ff_Gigantic_Squid.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, beach: true, hash: "58aced10" },
  { id: "040c", name: "Fly, Jumboman!", internalName: "MANUL02_G", file: "040c_Fly_Jumboman.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, hash: "da3aeb17" },
  { id: "0429", name: "Beach Umbrella", internalName: "PARASOL01_E", file: "0429_Beach_Umbrella.glb", kind: "large", tier: "large", heightUnits: 2.91, rooted: false, beach: true, label: "beach umbrella", hash: "38df7a3f" },
  { id: "042e", name: "Beach Umbrella", internalName: "PARASOL02_E", file: "042e_Beach_Umbrella.glb", kind: "large", tier: "large", heightUnits: 2.91, rooted: false, beach: true, label: "beach umbrella", hash: "fea862ca" },
  { id: "0434", name: "Spirit of Anger", internalName: "STATUE11_E", file: "0434_Spirit_of_Anger.glb", kind: "large", tier: "large", heightUnits: 3.24, rooted: false, label: "spirit of anger", hash: "56ce57cd" },
  { id: "0439", name: "Car Wash ", internalName: "GSTAND03_G", file: "0439_Car_Wash.glb", kind: "large", tier: "large", heightUnits: 2.35, rooted: false, label: "car wash", hash: "d5127a1a" },
  { id: "043b", name: "Scoreboard", internalName: "GROUND01_E", file: "043b_Scoreboard.glb", kind: "large", tier: "large", heightUnits: 2.39, rooted: false, label: "scoreboard", hash: "77bf1dab" },
  { id: "0448", name: "Flag Buoy", internalName: "LAKEFLAG01_D", file: "0448_Flag_Buoy.glb", kind: "medium", tier: "medium", heightUnits: 1.52, rooted: true, beach: true, label: "flag buoy", hash: "d28eef0b" },
  { id: "0452", name: "Stop Sign", internalName: "SIGN03_E", file: "0452_Stop_Sign.glb", kind: "large", tier: "large", heightUnits: 2.82, rooted: true, label: "stop sign", hash: "f497cbb0" },
  { id: "0457", name: "Log", internalName: "LOG01_D", file: "0457_Log.glb", kind: "stump", tier: "small", heightUnits: 0.6, rooted: true, hash: "eb7e7c7c" },
  { id: "0458", name: "Log Cabin", internalName: "LOGHOUSE01_G", file: "0458_Log_Cabin.glb", kind: "stump", tier: "small", heightUnits: 2, rooted: true, hash: "f4798d1c" },
  { id: "0464", name: "Flower Clock \"12\"", internalName: "FLOWERCLOCK03_D", file: "0464_Flower_Clock_12.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "fd92c41c" },
  { id: "0465", name: "Flower Clock \"3\"", internalName: "FLOWERCLOCK04_D", file: "0465_Flower_Clock_3.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "270e6781" },
  { id: "0466", name: "Flower Clock \"6\"", internalName: "FLOWERCLOCK05_D", file: "0466_Flower_Clock_6.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "e47d553e" },
  { id: "0467", name: "Flower Clock \"9\"", internalName: "FLOWERCLOCK06_D", file: "0467_Flower_Clock_9.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "efde3559" },
  { id: "0468", name: "Anchor", internalName: "ANCHOR01_F", file: "0468_Anchor.glb", kind: "building", tier: "building", heightUnits: 9.18, rooted: true, beach: true, hash: "717ca008" },
  { id: "046a", name: "Park Entrance ", internalName: "ARCH02_F", file: "046a_Park_Entrance.glb", kind: "building", tier: "building", heightUnits: 5.99, rooted: true, hash: "955fd1cd" },
  { id: "046e", name: "Silo", internalName: "FARMTANK01_G", file: "046e_Silo.glb", kind: "waterTower", tier: "large", heightUnits: 8, rooted: true, hash: "e7aac05d" },
  { id: "0478", name: "Garden Plant", internalName: "GREEN03_C", file: "0478_Garden_Plant.glb", kind: "bush", tier: "small", heightUnits: 0.6, rooted: true, hash: "23b80840" },
  { id: "047e", name: "Monument", internalName: "TVOFFICE02_G", file: "047e_Monument.glb", kind: "monolith", tier: "large", heightUnits: 3, rooted: true, hash: "26655a08" },
  { id: "0494", name: "Electric Jellyfish", internalName: "SEAJELLY01_C", file: "0494_Electric_Jellyfish.glb", kind: "small", tier: "small", heightUnits: 0.38, rooted: false, beach: true, label: "electric jellyfish", hash: "5cb24db5" },
  { id: "0497", name: "Lifeguard's Chair", internalName: "SEAKEEPER01_E", file: "0497_Lifeguard_s_Chair.glb", kind: "medium", tier: "medium", heightUnits: 2, rooted: false, beach: true, label: "lifeguard's chair", hash: "630be3b1" },
  { id: "0498", name: "Buoy", internalName: "SEAFLOAT01_C", file: "0498_Buoy.glb", kind: "large", tier: "large", heightUnits: 3.13, rooted: false, beach: true, label: "buoy", hash: "7d03fa35" },
  { id: "049c", name: "Cargo Container", internalName: "CONTAINER03_F", file: "049c_Cargo_Container.glb", kind: "large", tier: "large", heightUnits: 2.44, rooted: false, label: "cargo container", hash: "4278e4a6" },
  { id: "04a4", name: "Circus Sign", internalName: "CIRCUSSIDE03_E", file: "04a4_Circus_Sign.glb", kind: "building", tier: "building", heightUnits: 9.01, rooted: true, hash: "7cda4e15" },
  { id: "04a9", name: "Washing Machine", internalName: "LAUNDRYKI_E", file: "04a9_Washing_Machine.glb", kind: "medium", tier: "medium", heightUnits: 1.1, rooted: false, label: "washing machine", hash: "51d31de6" },
  { id: "04ba", name: "Magazine", internalName: "BOOK08_C", file: "04ba_Magazine.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, label: "magazine", hash: "88b8e514" },
  { id: "04c6", name: "Yellow Tulip", internalName: "TULIP03_C", file: "04c6_Yellow_Tulip.glb", kind: "small", tier: "small", heightUnits: 0.36, rooted: false, label: "yellow tulip", hash: "7a9c2beb" },
  { id: "04d8", name: "Torn Shoji", internalName: "SHOZI02_E", file: "04d8_Torn_Shoji.glb", kind: "medium", tier: "medium", heightUnits: 1.69, rooted: false, label: "torn shoji", hash: "d1b93b28" },
  { id: "04f0", name: "Lighthouse", internalName: "LIGHTHOUSE02_G", file: "04f0_Lighthouse.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, beach: true, hash: "df29a817" },
  { id: "04f4", name: "Boiler Room", internalName: "SENTO04_G", file: "04f4_Boiler_Room.glb", kind: "large", tier: "large", heightUnits: 3.29, rooted: false, label: "boiler room", hash: "d47426f2" },
  { id: "0502", name: "Palmistry Table", internalName: "FORTUNEREAD01_D", file: "0502_Palmistry_Table.glb", kind: "picnicTable", tier: "medium", heightUnits: 1.04, rooted: true, hash: "d3c69343" },
  { id: "0507", name: "Giant Daruma", internalName: "DARUMA03_G", file: "0507_Giant_Daruma.glb", kind: "cactus", tier: "small", heightUnits: 4, rooted: true, hash: "c7e78ff0" },
  { id: "0510", name: "Petroleum Tank", internalName: "OILTANK02_G", file: "0510_Petroleum_Tank.glb", kind: "waterTower", tier: "large", heightUnits: 6.65, rooted: true, hash: "6fedae10" },
  { id: "0515", name: "Windchime", internalName: "WINDBELL01_C", file: "0515_Windchime.glb", kind: "small", tier: "small", heightUnits: 0.23, rooted: false, label: "windchime", hash: "d8c7cb3c" },
  { id: "0526", name: "Huge Falling Rock", internalName: "ROLLINGSTONE02_E", file: "0526_Huge_Falling_Rock.glb", kind: "rock", tier: "small", heightUnits: 2, rooted: false, beach: true, inland: true, hash: "2c5c8832" },
  { id: "0530", name: "Grilled Fish", internalName: "DISHFOOD01_B", file: "0530_Grilled_Fish.glb", kind: "small", tier: "small", heightUnits: 0.1, rooted: false, beach: true, inland: true, label: "grilled fish", hash: "5f76a3b8" },
  { id: "0543", name: "Convenience Store", internalName: "CONVENI02_E", file: "0543_Convenience_Store.glb", kind: "building", tier: "building", heightUnits: 2.4, rooted: true, hash: "11af08c2" },
  { id: "0561", name: "Old Hotel Sign", internalName: "HOTELB04_E", file: "0561_Old_Hotel_Sign.glb", kind: "building", tier: "building", heightUnits: 4.57, rooted: true, hash: "ec332397" },
  { id: "0564", name: "Apartment Building #1", internalName: "MANSION03_G", file: "0564_Apartment_Building_1.glb", kind: "building", tier: "building", heightUnits: 2.4, rooted: true, hash: "962fa28c" },
  { id: "0571", name: "Suspension Bridge", internalName: "BRIDGE05_G", file: "0571_Suspension_Bridge.glb", kind: "large", tier: "large", heightUnits: 3.97, rooted: true, label: "suspension bridge", hash: "389c2c1f" },
  { id: "0574", name: "Kimura Residence", internalName: "OUCHI08_F", file: "0574_Kimura_Residence.glb", kind: "building", tier: "building", heightUnits: 7.55, rooted: true, hash: "fd4f14f5" },
  { id: "0584", name: "Flower Girl", internalName: "MANMASTER04_D", file: "0584_Flower_Girl.glb", kind: "bush", tier: "small", heightUnits: 1.57, rooted: true, hash: "76d35f0c" },
  { id: "0591", name: "Golfer Guy", internalName: "MANOSAN01B_D", file: "0591_Golfer_Guy.glb", kind: "medium", tier: "medium", heightUnits: 1.41, rooted: false, label: "golfer guy", hash: "ec55b6e2" },
  { id: "0596", name: "Giant Squid", internalName: "OCTOPUS03_F", file: "0596_Giant_Squid.glb", kind: "large", tier: "large", heightUnits: 2.77, rooted: false, beach: true, label: "giant squid", hash: "88ad7ad3" },
  { id: "0597", name: "Giant Octopus", internalName: "OCTOPUS04_F", file: "0597_Giant_Octopus.glb", kind: "building", tier: "building", heightUnits: 12, rooted: true, beach: true, hash: "9a48d530" },
  { id: "05af", name: "Green Balloon", internalName: "BALLOON06_C", file: "05af_Green_Balloon.glb", kind: "medium", tier: "medium", heightUnits: 1.14, rooted: false, label: "green balloon", hash: "a90bdc24" },
  { id: "05ba", name: "Xmas Tree", internalName: "MIX02_D", file: "05ba_Xmas_Tree.glb", kind: "conifer", tier: "medium", heightUnits: 4, rooted: true, hash: "1575544a" },
  { id: "05bf", name: "Royal Present", internalName: "PRE03_D", file: "05bf_Royal_Present.glb", kind: "medium", tier: "medium", heightUnits: 0.6, rooted: false, label: "royal present", hash: "1d3a30b8" },
  { id: "05c0", name: "Royal Present", internalName: "PRE04_D", file: "05c0_Royal_Present.glb", kind: "building", tier: "building", heightUnits: 5.73, rooted: true, hash: "016cf4a4" },
  { id: "05df", name: "Canada", internalName: "ED003_G", file: "05df_Canada.glb", kind: "large", tier: "large", heightUnits: 3.07, rooted: false, label: "canada", hash: "852dc8d9" },
  { id: "05ed", name: "Panama", internalName: "ED017_G", file: "05ed_Panama.glb", kind: "small", tier: "small", heightUnits: 0.29, rooted: false, label: "panama", hash: "e4b7cd81" },
  { id: "05f2", name: "Mexico", internalName: "ED022_G", file: "05f2_Mexico.glb", kind: "medium", tier: "medium", heightUnits: 1.61, rooted: false, label: "mexico", hash: "33a99920" },
  { id: "05fb", name: "Brazil", internalName: "ED031_G", file: "05fb_Brazil.glb", kind: "large", tier: "large", heightUnits: 2.16, rooted: false, label: "brazil", hash: "4494c1d7" },
  { id: "0614", name: "Indonesia", internalName: "ED056_G", file: "0614_Indonesia.glb", kind: "large", tier: "large", heightUnits: 2.53, rooted: false, label: "indonesia", hash: "4cb04a2c" },
  { id: "0630", name: "China", internalName: "ED084_G", file: "0630_China.glb", kind: "large", tier: "large", heightUnits: 2.46, rooted: false, label: "china", hash: "be8d0674" },
  { id: "064f", name: "Senegal", internalName: "ED115_G", file: "064f_Senegal.glb", kind: "small", tier: "small", heightUnits: 0.32, rooted: false, label: "senegal", hash: "f8670712" },
  { id: "066c", name: "Andorra", internalName: "ED144_G", file: "066c_Andorra.glb", kind: "small", tier: "small", heightUnits: 0.19, rooted: false, label: "andorra", hash: "098607d9" },
  { id: "066d", name: "England", internalName: "ED145_G", file: "066d_England.glb", kind: "medium", tier: "medium", heightUnits: 0.63, rooted: false, label: "england", hash: "5e944db9" },
  { id: "0680", name: "Finland", internalName: "ED164_G", file: "0680_Finland.glb", kind: "medium", tier: "medium", heightUnits: 0.81, rooted: false, label: "finland", hash: "ac3ebad0" },
  { id: "069a", name: "Moldova", internalName: "ED190_G", file: "069a_Moldova.glb", kind: "small", tier: "small", heightUnits: 0.19, rooted: false, label: "moldova", hash: "008c5ba9" },
  { id: "069d", name: "Antarctica", internalName: "ED193_G", file: "069d_Antarctica.glb", kind: "large", tier: "large", heightUnits: 2.53, rooted: false, label: "antarctica", hash: "cb069108" },
];
